//Windows
// pipeline {
//     agent any
//     environment {
//         CONTAINER_IMAGE = 'decide-image'
//     }
//     stages {
//         stage('Checkout') {
//             steps {
//                 checkout scm
//             }
//         }
//         stage('Build Docker Image') {
//             steps {
//                 dir('docker/') {
//                     bat 'docker build -t %CONTAINER_IMAGE% .'
//                 }
//             }
//         }
//         stage('Scan with Trivy') {
//             steps {
//                 script {
//                     bat trivy --version
                    
//                 }
//             }
//         }
//     }
// }

//Linux
pipeline {
    agent any
    environment {
        CONTAINER_IMAGE = 'decide-image'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
              sh 'docker build docker/ -t $CONTAINER_IMAGE .'
            }
        }
        stage('Scan with Trivy') {
            steps {
                script {
                    // Scan the Docker image with Trivy
                    sh "trivy --exit-code 1 --severity HIGH,CRITICAL --no-progress $CONTAINER_IMAGE"
                }
            }
        }
    }
}
